-- GramVault SQLite schema.
--
-- Migration approach: this is intentionally a single idempotent script
-- (CREATE TABLE IF NOT EXISTS everywhere). Call gramvault.db.session.init_db()
-- to apply it. For a single-user local-first app at v1, this is sufficient;
-- if the schema needs to evolve later, add numbered `migrations/NNN_*.sql`
-- files and a small version-tracking table rather than hand-editing this
-- file destructively. Don't over-engineer this for now.

PRAGMA foreign_keys = ON;

-- Instagram authors/creators whose content was saved.
CREATE TABLE IF NOT EXISTS authors (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    username     TEXT NOT NULL UNIQUE,
    full_name    TEXT,
    profile_url  TEXT,
    avatar_path  TEXT,
    created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- One saved post/reel/carousel. May have multiple media_files (carousel).
CREATE TABLE IF NOT EXISTS items (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    external_id         TEXT UNIQUE, -- Instagram shortcode/post id, if known
    author_id           INTEGER REFERENCES authors(id) ON DELETE SET NULL,
    media_type          TEXT NOT NULL CHECK (media_type IN ('photo', 'video', 'reel', 'carousel')),
    caption             TEXT,
    permalink           TEXT,
    taken_at            TEXT, -- ISO8601 timestamp of original post, if known
    imported_at         TEXT NOT NULL DEFAULT (datetime('now')),
    import_job_id       INTEGER REFERENCES import_jobs(id) ON DELETE SET NULL,
    enrichment_status   TEXT NOT NULL DEFAULT 'pending'
                         CHECK (enrichment_status IN ('pending', 'running', 'done', 'failed')),
    raw_metadata_json   TEXT -- original exporter JSON blob, for anything unmapped
);

CREATE INDEX IF NOT EXISTS idx_items_author_id ON items(author_id);
CREATE INDEX IF NOT EXISTS idx_items_enrichment_status ON items(enrichment_status);
CREATE INDEX IF NOT EXISTS idx_items_import_job_id ON items(import_job_id);

-- Individual media files belonging to an item (photo, or video + optional
-- extracted keyframes are tracked separately by the enrichment pipeline,
-- not as rows here -- this table is the "source" files only).
CREATE TABLE IF NOT EXISTS media_files (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id             INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    file_path           TEXT NOT NULL,
    media_type          TEXT NOT NULL CHECK (media_type IN ('photo', 'video')),
    sequence_index      INTEGER NOT NULL DEFAULT 0, -- ordering within a carousel
    width               INTEGER,
    height              INTEGER,
    duration_seconds    REAL, -- videos only
    transcript          TEXT, -- faster-whisper output, videos only (Agent A3)
    vision_caption      TEXT, -- llava output (Agent A3)
    checksum            TEXT
);

CREATE INDEX IF NOT EXISTS idx_media_files_item_id ON media_files(item_id);

-- Free-form tags, either hashtags pulled from captions, auto-generated by
-- the AI pipeline, or added manually by the user in the gallery UI.
CREATE TABLE IF NOT EXISTS tags (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    name    TEXT NOT NULL UNIQUE,
    kind    TEXT NOT NULL DEFAULT 'auto' CHECK (kind IN ('auto', 'manual', 'hashtag'))
);

CREATE TABLE IF NOT EXISTS item_tags (
    item_id     INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    tag_id      INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (item_id, tag_id)
);

-- Tracks a single "import a ZIP export" run, for progress + resumability.
CREATE TABLE IF NOT EXISTS import_jobs (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    source_path         TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending', 'running', 'done', 'failed')),
    total_items         INTEGER NOT NULL DEFAULT 0,
    processed_items     INTEGER NOT NULL DEFAULT 0,
    failed_items        INTEGER NOT NULL DEFAULT 0,
    error_message       TEXT,
    started_at          TEXT,
    finished_at         TEXT,
    created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Chat sessions + messages. Agent A4 owns the actual RAG logic; this is
-- just the persistence shape.
CREATE TABLE IF NOT EXISTS chat_sessions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title       TEXT,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id  INTEGER NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role        TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content     TEXT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON chat_messages(session_id);

-- Citations attached to an assistant message, pointing back at the
-- library item (and optionally the specific media file) that grounded it.
CREATE TABLE IF NOT EXISTS chat_citations (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    message_id      INTEGER NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    item_id         INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    media_file_id   INTEGER REFERENCES media_files(id) ON DELETE SET NULL,
    snippet         TEXT
);

CREATE INDEX IF NOT EXISTS idx_chat_citations_message_id ON chat_citations(message_id);
